// --------------------------------------------------------------
// -                       Custom Scripts                       -
// --------------------------------------------------------------

// ----------------------- Main Scripts -----------------------
npc: npc/custom/Ragnarok/Main/Functions.txt
npc: npc/custom/Ragnarok/Main/Security.txt
//npc: npc/custom/Ragnarok/Main/ArmorEnchanter.txt
//npc: npc/custom/Ragnarok/Main/WeaponEnchanter.txt
npc: npc/custom/Ragnarok/Main/Hourly.txt
npc: npc/custom/Ragnarok/Main/Transparency.txt
npc: npc/custom/Ragnarok/Main/ZenyRanking.txt
npc: npc/custom/Ragnarok/Main/autoattack.txt
npc: npc/custom/Ragnarok/Main/VIPManager.txt
npc: npc/custom/Ragnarok/Main/DailySupply.txt
npc: npc/custom/Ragnarok/Main/JobMaster.txt
npc: npc/custom/Ragnarok/Main/Warper.txt
npc: npc/custom/Ragnarok/Main/Healer.txt
npc: npc/custom/Ragnarok/Main/PvPWarper.txt
npc: npc/custom/Ragnarok/Main/AllInOneNPC.txt
npc: npc/custom/Ragnarok/Main/Race99.txt
npc: npc/custom/Ragnarok/Main/PotionConverter.txt
npc: npc/custom/Ragnarok/Main/Freebie.txt

//-- Battlepass Scripts
//---------------------------------------------------------------
//npc: npc/custom/Ragnarok/Battlepass/battlepass.txt
//npc: npc/custom/Ragnarok/Battlepass/serverrefresh.txt
//npc: npc/custom/Ragnarok/Battlepass/battlepass_quest.txt

// ----------------------- Event Scripts -----------------------
//npc: npc/custom/Ragnarok/Event/GachaMachineZeny.txt
// ----------------------- Shops Scripts -----------------------
// ----------------------- Warps Scripts -----------------------

// ----------------------- Quest Scripts -----------------------

// ----------------------- Mapflag Scripts -----------------------
npc: npc/custom/Ragnarok/Mapflag/NoItem.txt







